name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  ci:
    name: Build and test epb
    runs-on: ${{ matrix.os }}
    container: erlang:${{ matrix.otp }}

    strategy:
      matrix:
        otp: ["24.0"]
        os: [centos-latest, ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    env:
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Proper
        uses: actions/checkout@v2
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        env:
          ERL_LIBS: "./"
        run: |
          set -xv
          make
          make tests
