name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  ubuntu:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp: ["22", "23", "24"]
        os: [ubuntu-latest]
      fail-fast: false

    container:
      image: erlang:${{ matrix.otp }}

    env:
      ERL_LIBS: './'
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Proper
        uses: actions/checkout@v2
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        run: |
          make
          make tests
