name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  build:

    name: Build and test epb
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otpvsn: ['24.0']
        os: [ubuntu-latest]
      fail-fast: false

    env:
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Proper testing
        uses: actions/checkout@v2
        with:
          repository: https://github.com/proper-testing/proper.git
          path: './'
      - name: Setup Erlang
        uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: ${{ matrix.otpvsn }}
      - name: Run test
        run: |
          set -xv
          make
          make test
        env:
          ERL_LIBS: './proper'
