name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  ci:
    name: Build and test epb
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp: ["23"]
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    env:
      ERL_LIBS: './'
    steps:
      - name: Setup Erlang
        uses: bajankristof/setup-erlang@master
        with:
          otp-version: ${{ matrix.otp }}
      - uses: actions/checkout@v2
      - name: Checkout Proper
        uses: actions/checkout@v2
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        run: |
          make
          make tests
