name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  windows:
    name: Test on Windows
    runs-on: windows-latest

    strategy:
      matrix:
        otp: ["24"]
      fail-fast: false

    env:
      ERL_LIBS: './'

    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        run: choco install erlang
      - name: Checkout Proper
        uses: actions/checkout@v2
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        run: |
          .\rebar3 compile
