name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    name: Build and test epb
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otpvsn: [20, 24]
        os: [centos-latest, ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    container:
      image: erlang:${{ matrix.otpvsn }}

    env:
      VERBOSE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Erlang ${{ matrix.otpvsn }}
        # TODO: test with protobuf (in the container)
        run: |
          set -xv
          make
          make test
